/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://66brve7gsbdjjmzfe6ylvuwcg4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-heakadw5kvdyzlr5pglqshv7oe",
    "aws_cognito_identity_pool_id": "eu-central-1:86cc4c4a-1230-42b4-b3bd-c17213e4d906",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_hSm6OjOde",
    "aws_user_pools_web_client_id": "21gh6m24kc48o31leblgmmvdhq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
